seed: 111
env_seed: 1
eval_seed: 2

num_train_steps: 50_000
num_envs: 128

agent:
  learning_rate: 3e-4
  start_eps: 1.0
  end_eps: 0.0
  exploration_steps: 50_000

network:
  num_layers: 3
  mlp_num_layers: 1
  embedding_size: 128
  num_heads: 4

environment:
  # Data can be generated via utils.dag.generate_dataset
  train_samples_path: "path/to/train_data.csv"

  prior:
    type: uniform

  likelihood:
    type: linear_gaussian_score # Or bge_score
    prior_mean: 0.0
    prior_scale: 1.0
    obs_scale: 0.316 # sqrt(0.1)

metrics:
  n_rounds: 10
  batch_size: 29281

logging:
  track_each: 100 # in terms of total training steps, not divided by num_envs
  eval_each: 500 # in terms of total training steps, not divited by num_envs
  metric_buffer_size: 1_000_000
  tqdm_print_rate: 100
  use_writer: true
  log_dir: null # If null, dir will be automatically created
  checkpoint_dir: null # If null, dir will be automatically created

# Technical information for writer
writer:
  writer_type: wandb # wandb, trackio or null (no logging online)
  save_locally: false # Save metrics locally or not
  entity: null
  project: dag-sampling

# Technical information for hydra
hydra:
  run:
    dir: ./tmp/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: ./tmp/${now:%Y-%m-%d}/${now:%H-%M-%S}
